service: serverless-qr-generator

useDotenv: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-jest-plugin

package:
  patterns:
    - '!__tests__'
    - '!.github'

custom:
  serverless-offline:
    httpPort: 4001

provider:
  name: aws
  runtime: nodejs22.x
  profile: ${env:AWS_PROFILE, 'default'}
  stage: ${opt:stage, 'production'}
  region: ${opt:region, 'eu-west-1'}
  iam:
    role: ${env:AWS_IAM_ROLE, ''}
  apiGateway:
    shouldStartNameWithService: true

functions:
  generateQR:
    handler: handler.generateQR
    events:
      - http:
          path: generate
          method: post
          cors: true