'use strict';

// tests for generateQR
// Generated by serverless-jest-plugin

import * as handler from '../handler';
import * as jestPlugin from 'serverless-jest-plugin';

const lambdaWrapper = jestPlugin.lambdaWrapper;

const wrapped = lambdaWrapper.wrap(handler, { handler: 'generateQR' });

describe('generateQR', () => {
  beforeAll((done) => {
//  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('implement tests here', () => {
    return wrapped.run({
      body: JSON.stringify({
        'url': 'https://www.google.com',
      })
    }).then((response) => {
      expect(response.headers['Content-Type']).toBe('image/svg+xml');
    });
  });
});
